import { MovieDetails } from './movie-details';

export const MOCKDATA: MovieDetails[] = [
  {
    id: 'mockdata',
     selected: false,
   movieTitle: 'MockMovie',
    genre: 'action',
    rating: 2
  },
  {
    id: 'mockdata',
     selected: false,
   movieTitle: 'MockMovie1',
    genre: 'action',
    rating: 3
  },
  {
    id: 'mockdata',
     selected: false,
   movieTitle: 'MockMovie2',
    genre: 'action',
    rating: 6
  },
  {id: 'mockdata' , selected: false, movieTitle: 'MockMovie3', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie4', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie5', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie6', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie7', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie8', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie9', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie10', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie11', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie12', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie13', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie14', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie15', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie16', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie17', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie18', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie20', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie21', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie22', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie24', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie25', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie26', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie27', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie28', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie29', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie30', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie31', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie32', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie34', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie35', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie36', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie37', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie38', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie39', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie40', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie41', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie42', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie43', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie44', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie45', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie46', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie47', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie48', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie49', genre: 'action', rating: 1},
  {id: 'mockdata', selected: false, movieTitle: 'MockMovie50', genre: 'action', rating: 1}
];
