import { MovieDetails } from './movie-details';

export const MOCKDATA: MovieDetails[] = [
  {
    id: 'mockdata',
     selected: false,
   movieTitle: 'MockMovie',
    genre: 'action',
    rating: 2
  },
  {
    id: 'mockdata',
     selected: false,
   movieTitle: 'MockMovie1',
    genre: 'action',
    rating: 3
  },
  {
    id: 'mockdata',
     selected: false,
   movieTitle: 'MockMovie2',
    genre: 'action',
    rating: 6
  },
  {id: 'mockdata1' , selected: false, movieTitle: 'MockMovie3', genre: 'action', rating: 1},
  {id: 'mockdata2', selected: false, movieTitle: 'MockMovie4', genre: 'action', rating: 1},
  {id: 'mockdata3', selected: false, movieTitle: 'MockMovie5', genre: 'action', rating: 1},
  {id: 'mockdata4', selected: false, movieTitle: 'MockMovie6', genre: 'action', rating: 1},
  {id: 'mockdata5', selected: false, movieTitle: 'MockMovie7', genre: 'action', rating: 1},
  {id: 'mockdata6', selected: false, movieTitle: 'MockMovie8', genre: 'action', rating: 1},
  {id: 'mockdata7', selected: false, movieTitle: 'MockMovie9', genre: 'action', rating: 1},
  {id: 'mockdata8', selected: false, movieTitle: 'MockMovie10', genre: 'action', rating: 1},
  {id: 'mockdata9', selected: false, movieTitle: 'MockMovie11', genre: 'action', rating: 1},
  {id: 'mockdata10', selected: false, movieTitle: 'MockMovie12', genre: 'action', rating: 1},
  {id: 'mockdata11', selected: false, movieTitle: 'MockMovie13', genre: 'action', rating: 1},
  {id: 'mockdata12', selected: false, movieTitle: 'MockMovie14', genre: 'action', rating: 1},
  {id: 'mockdata13', selected: false, movieTitle: 'MockMovie15', genre: 'action', rating: 1},
  {id: 'mockdata14', selected: false, movieTitle: 'MockMovie16', genre: 'action', rating: 1},
  {id: 'mockdata15', selected: false, movieTitle: 'MockMovie17', genre: 'action', rating: 1},
  {id: 'mockdata16', selected: false, movieTitle: 'MockMovie18', genre: 'action', rating: 1},
  {id: 'mockdata17', selected: false, movieTitle: 'MockMovie20', genre: 'action', rating: 1},
  {id: 'mockdata18', selected: false, movieTitle: 'MockMovie21', genre: 'action', rating: 1},
  {id: 'mockdata19', selected: false, movieTitle: 'MockMovie22', genre: 'action', rating: 1},
  {id: 'mockdata20', selected: false, movieTitle: 'MockMovie24', genre: 'action', rating: 1},
  {id: 'mockdata21', selected: false, movieTitle: 'MockMovie25', genre: 'action', rating: 1},
  {id: 'mockdata22', selected: false, movieTitle: 'MockMovie26', genre: 'action', rating: 1},
  {id: 'mockdata23', selected: false, movieTitle: 'MockMovie27', genre: 'action', rating: 1},
  {id: 'mockdata24', selected: false, movieTitle: 'MockMovie28', genre: 'action', rating: 1},
  {id: 'mockdata25', selected: false, movieTitle: 'MockMovie29', genre: 'action', rating: 1},
  {id: 'mockdata26', selected: false, movieTitle: 'MockMovie30', genre: 'action', rating: 1},
  {id: 'mockdata27', selected: false, movieTitle: 'MockMovie31', genre: 'action', rating: 1},
  {id: 'mockdata28', selected: false, movieTitle: 'MockMovie32', genre: 'action', rating: 1},
  {id: 'mockdata29', selected: false, movieTitle: 'MockMovie34', genre: 'action', rating: 1},
  {id: 'mockdata30', selected: false, movieTitle: 'MockMovie35', genre: 'action', rating: 1},
  {id: 'mockdata31', selected: false, movieTitle: 'MockMovie36', genre: 'action', rating: 1},
  {id: 'mockdata32', selected: false, movieTitle: 'MockMovie37', genre: 'action', rating: 1},
  {id: 'mockdata33', selected: false, movieTitle: 'MockMovie38', genre: 'action', rating: 1},
  {id: 'mockdata34', selected: false, movieTitle: 'MockMovie39', genre: 'action', rating: 1},
  {id: 'mockdata35', selected: false, movieTitle: 'MockMovie40', genre: 'action', rating: 1},
  {id: 'mockdata36', selected: false, movieTitle: 'MockMovie41', genre: 'action', rating: 1},
  {id: 'mockdata37', selected: false, movieTitle: 'MockMovie42', genre: 'action', rating: 1},
  {id: 'mockdata38', selected: false, movieTitle: 'MockMovie43', genre: 'action', rating: 1},
  {id: 'mockdata39', selected: false, movieTitle: 'MockMovie44', genre: 'action', rating: 1},
  {id: 'mockdata40', selected: false, movieTitle: 'MockMovie45', genre: 'action', rating: 1},
  {id: 'mockdata41', selected: false, movieTitle: 'MockMovie46', genre: 'action', rating: 1},
  {id: 'mockdata42', selected: false, movieTitle: 'MockMovie47', genre: 'action', rating: 1},
  {id: 'mockdata43', selected: false, movieTitle: 'MockMovie48', genre: 'action', rating: 1},
  {id: 'mockdata44', selected: false, movieTitle: 'MockMovie49', genre: 'action', rating: 1},
  {id: 'mockdata45', selected: false, movieTitle: 'MockMovie50', genre: 'action', rating: 1}
];
